### ISSUE TITLE
Clean code resource

### ISSUE THREAD

**Issue by VincentYeh-dev** [nfu-irs-lab/docs#5]
https://medium.com/%E6%89%8B%E5%AF%AB%E7%AD%86%E8%A8%98/clean-code-index-51e209cc47db

**Comment by ziteh** [comment]
感謝提供資源，已加入篇章：https://github.com/nfu-irs-lab/docs#%E7%84%A1%E6%9A%87%E7%9A%84%E7%A8%8B%E5%BC%8F%E7%A2%BC-Clean-Code
